import ContentPages from "./ContentPages"

export default function ArrayPages({getDescription, getTitleText}){

    return(
    <>
        <ContentPages img="assets/pages/adobe-color.jpg" title="Adobe Color" description="Anteriormente conocida como Adobe Kuler, es una herramienta en línea que permite a los usuarios crear, explorar y compartir paletas de colores. Permite generar esquemas de colores utilizando diferentes métodos como reglas de color, rueda de color y muestras de imágenes. Los usuarios pueden ajustar y personalizar los colores según sus preferencias y luego descargar las paletas para su uso en proyectos de diseño gráfico, desarrollo web, ilustración y más. Adobe Color ofrece una plataforma comunitaria donde los usuarios pueden explorar paletas creadas por otros, compartir sus propias creaciones y obtener inspiración para sus proyectos creativos. Es una herramienta valiosa para diseñadores y artistas que buscan experimentar con el color y crear armonías visuales impactantes." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/Autoprefixer.jpg" title="Auto-Prefixer" description="Autoprefixer es una herramienta que facilita la escritura de CSS al agregar automáticamente los prefijos de los proveedores necesarios para garantizar la compatibilidad con diferentes navegadores. Simplemente ingresa tu CSS sin prefijos, y Autoprefixer analiza tu código y agrega los prefijos específicos del navegador según la compatibilidad que desees. Esto significa que no necesitas recordar todos los prefijos específicos de cada navegador, lo que ahorra tiempo y evita errores. Además, Autoprefixer se integra fácilmente con herramientas de construcción como Gulp, Grunt y webpack, lo que facilita su incorporación en tu flujo de trabajo de desarrollo. Con Autoprefixer, puedes escribir CSS moderno y mantener la compatibilidad con versiones anteriores de navegadores sin problemas." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/CSS_clip-path_maker_by_Bennett_Feely.jpg" title="CSS clip path maker by Bennett Feely" description="Es una herramienta en línea que permite a los desarrolladores crear formas personalizadas para recortar o enmascarar elementos HTML utilizando la propiedad CSS clip-path. Con esta herramienta, los usuarios pueden ajustar fácilmente las coordenadas y los valores de las formas, así como experimentar con diferentes formas predefinidas. Esto simplifica el proceso de creación de efectos de recorte y enmascaramiento complejos, lo que resulta en diseños más dinámicos y visualmente atractivos en sitios web y aplicaciones web." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/css-Gradient.jpg" title="CSS Gradient" description="Es una página web que proporciona una herramienta para generar códigos CSS para degradados. Permite a los usuarios crear degradados personalizados mediante una interfaz intuitiva, seleccionando colores y ajustando la dirección, el tipo y otros parámetros del degradado. La página ofrece una variedad de opciones, incluyendo degradados lineales y radiales, así como múltiples colores y puntos de parada. Los usuarios pueden previsualizar instantáneamente los degradados generados y copiar el código CSS correspondiente para usarlo en sus proyectos. CSS Gradient es útil para diseñadores web y desarrolladores que desean crear degradados visualmente atractivos y personalizados sin necesidad de escribir código CSS manualmente. Además, la página es gratuita y no requiere registro, lo que la hace accesible y fácil de usar para cualquier persona que necesite aplicar degradados en sus diseños web." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/cubic_bezier.jpg" title="Cubic Bezier" description="Cubic Bezier es una herramienta en línea que permite a los desarrolladores y diseñadores crear y visualizar curvas de Bezier cúbicas de una manera interactiva. Las curvas de Bezier cúbicas son útiles para definir trayectorias suaves y animaciones en el diseño web y gráfico. Con Cubic Bezier, los usuarios pueden ajustar los puntos de control de las curvas de Bezier en un lienzo visual y ver los cambios en tiempo real. Esto facilita la experimentación con diferentes formas de curvas y ayuda a encontrar la configuración óptima para lograr efectos visuales deseados. La herramienta también proporciona código CSS que representa la curva de Bezier configurada, lo que facilita su implementación en proyectos web. En resumen, Cubic Bezier es una herramienta valiosa para crear y ajustar curvas de Bezier cúbicas de manera rápida y eficiente en el diseño web y gráfico." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/favicon_generator.jpg" title="Favicon Generator" description="Es una herramienta que permite crear favicons, que son pequeños íconos que representan un sitio web y aparecen en la pestaña del navegador y en los marcadores. Esta herramienta toma una imagen de entrada y genera múltiples versiones en diferentes tamaños y formatos compatibles con varios navegadores y dispositivos. Esto facilita la creación de favicons personalizados para mejorar la identidad visual y la experiencia del usuario en la web." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/flaticon.jpg" title="Flaticon" description="Un sitio web que ofrece una amplia colección de iconos vectoriales y otros recursos gráficos para su uso en diseño gráfico, diseño web, presentaciones, aplicaciones móviles y más. Los usuarios pueden explorar y descargar iconos en diferentes formatos y estilos, incluyendo SVG, PNG, EPS y PSD. Además, Flaticon proporciona herramientas para personalizar y editar los iconos según las necesidades del usuario. También ofrece la opción de crear y guardar colecciones personalizadas de iconos para un acceso rápido y fácil. En resumen, Flaticon es una plataforma popular y útil para encontrar y descargar iconos de alta calidad para una variedad de proyectos creativos." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/google_fonts.jpg" title="Google Fonts" description="Google Fonts es un servicio gratuito ofrecido por Google que permite a los desarrolladores web incrustar fuentes personalizadas en sus sitios web de manera fácil y rápida. Ofrece una amplia variedad de fuentes de alta calidad, incluyendo opciones para varios idiomas y scripts. Los usuarios pueden seleccionar las fuentes deseadas, obtener el código de incrustación y agregarlo a sus sitios web con solo unos pocos clics. Esto facilita la mejora del aspecto visual y la legibilidad de los sitios web sin necesidad de descargar o instalar fuentes adicionales en los dispositivos de los usuarios. En resumen, Google Fonts simplifica el proceso de integración de fuentes personalizadas, lo que permite a los desarrolladores mejorar la estética y la experiencia de lectura de sus sitios web de manera eficiente." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/online_convert.jpg" title="Online Convert" description="Es un servicio web que permite convertir una amplia variedad de archivos entre diferentes formatos. Los usuarios pueden cargar archivos desde su dispositivo o proporcionar enlaces URL, y luego seleccionar el formato de destino deseado. La plataforma admite conversiones de archivos de audio, video, documentos, imágenes, libros electrónicos y más. También ofrece opciones avanzadas para ajustar la configuración de conversión, como la calidad de compresión para archivos de imagen o la tasa de bits para archivos de audio y video. Una vez completada la conversión, los usuarios pueden descargar los archivos resultantes directamente desde el sitio web. Online Convert es fácil de usar y no requiere instalación de software adicional. Además, ofrece una amplia gama de formatos de archivo compatibles, lo que lo convierte en una herramienta conveniente para quienes necesitan convertir archivos de manera rápida y sencilla." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/regexr.jpg" title="Regexr" description="Es una página web que ofrece una herramienta interactiva para crear, probar y aprender expresiones regulares. Permite a los usuarios escribir expresiones regulares y ver cómo coinciden con diferentes cadenas de texto en tiempo real. Además, ofrece características como resaltado de sintaxis, sugerencias de código, explicaciones detalladas de cada parte de la expresión regular y opciones de configuración avanzada. Regexr es útil para desarrolladores web, programadores y cualquier persona que necesite trabajar con expresiones regulares, ya que simplifica el proceso de creación y depuración de patrones de búsqueda de texto. Su interfaz intuitiva y amigable hace que sea fácil de usar incluso para aquellos que no están familiarizados con las expresiones regulares." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/Toptal_css_minifer.jpg" title="Toptal CSS Minifer" description="Es una herramienta en línea que permite comprimir y minificar código CSS. Al ingresar tu código CSS en el campo de entrada, la herramienta eliminará espacios en blanco, comentarios y otros caracteres no esenciales para reducir el tamaño del archivo CSS. Esto ayuda a mejorar el rendimiento de carga de la página web al reducir el tamaño de los archivos CSS, lo que resulta en tiempos de carga más rápidos. Además, la herramienta puede ayudar a mejorar la optimización de motores de búsqueda al reducir el tamaño total de los recursos de la página web. Es una herramienta útil para desarrolladores web que desean optimizar el rendimiento y la eficiencia de sus sitios." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/UTOPIA_fluid_type_scale_calculator.jpg" title="UTOPIA Fluid Type Scale Calculator" description="Es una herramienta en línea que permite a los diseñadores y desarrolladores calcular escalas tipográficas fluidas para sus proyectos web. Con esta herramienta, los usuarios pueden especificar el tamaño de fuente base, así como el rango de tamaños de fuente mínimo y máximo que desean para sus diseños responsivos. UTOPIA ajusta automáticamente los tamaños de fuente dentro del rango especificado en función del ancho de la ventana del navegador o del dispositivo del usuario, lo que garantiza una experiencia de lectura óptima en diferentes dispositivos y pantallas. Esta calculadora ayuda a mantener la legibilidad y la estética visual de los textos en páginas web adaptativas, permitiendo a los diseñadores crear diseños coherentes y agradables para los usuarios en una variedad de dispositivos y tamaños de pantalla." getDescription={getDescription} getTitleText={getTitleText}/>

        <ContentPages img="assets/pages/wave_generator_mini.jpg" title="Wave Generator" description="Una herramienta que permite generar gráficos vectoriales escalables (SVG) de ondas o formas onduladas personalizadas. Utiliza parámetros ajustables como amplitud, longitud de onda y frecuencia para crear ondas de diferentes estilos y formas. Estas formas pueden ser utilizadas en diseño web, gráficos de datos, animaciones SVG y otros proyectos creativos para agregar interés visual y dinamismo." getDescription={getDescription} getTitleText={getTitleText}/>
    </>)
}